#ifndef NRF24L01P_MISTAKES_H_
#define NRF24L01P_MISTAKES_H_

/*
 @file nrf24l01p_mistakes.h
 @brief Contains defines with all mistakes codes that nrf24l01p library uses
 */

// @brief Mistakes code offset. Can be redefined in the source code (Should be higher than #include "nrf24l01p.h") by the user to get mistakes in any desired range.
#ifndef NRF24L01P_NAMESPACE_OFFSET
    #define NRF24L01P_NAMESPACE_OFFSET              (600U)
#endif

#define NRF24_WRONG_CHANNEL_FREQUENCY_Err           (1U + NRF24L01P_NAMESPACE_OFFSET)
#define NRF24_WRONG_PAYLOAD_SIZE_Err                (2U + NRF24L01P_NAMESPACE_OFFSET)
#define NRF24_DEVICE_IS_NOT_CONNECTED_Err           (3U + NRF24L01P_NAMESPACE_OFFSET)
#define NRF24_CE_HIGH_FUNCTION_IS_MISSING_Err       (4U + NRF24L01P_NAMESPACE_OFFSET)
#define NRF24_CE_LOW_FUNCTION_IS_MISSING_Err        (5U + NRF24L01P_NAMESPACE_OFFSET)
#define NRF24_CSN_HIGH_FUNCTION_IS_MISSING_Err      (6U + NRF24L01P_NAMESPACE_OFFSET)
#define NRF24_CSN_LOW_FUNCTION_IS_MISSING_Err       (7U + NRF24L01P_NAMESPACE_OFFSET)
#define NRF24_SPI_WRITE_FUNCTION_IS_MISSING_Err     (8U + NRF24L01P_NAMESPACE_OFFSET)
#define NRF24_INSTANCE_WAS_NOT_INITIALIZED_Err      (9U + NRF24L01P_NAMESPACE_OFFSET)
#define NRF24_WRONG_RETRANSMIT_COUNT_Err            (10U + NRF24L01P_NAMESPACE_OFFSET)
#define NRF24_WRONG_MESSAGE_SIZE_Err                (11U + NRF24L01P_NAMESPACE_OFFSET)
#define NRF24_WRONG_PIPE_NUMBER_Err                 (12U + NRF24L01P_NAMESPACE_OFFSET)

#endif /* NRF24L01P_MISTAKES_H_ */
